#!/usr/bin/env bash

function print_help() {
    echo "\
Usage: mrunner task.sh [arg1, ...]

mrunner envrionment variables to export: 
    NUM_NODES   : number of nodes
    MASTER_ADDR : address of master node
    NODE_RANK   : rank of each node
    TASK_ID     : task id

mrunner will read some meta infomation in task scirpt like this:
#MRUNNER --NODES=10.114.166.21[1-3],10.114.166.215
#MRUNNER --CONTAINER=linseer_megatron_yt
"
}

if [[ $# -le 0 || $1 == "-h" || $1 == "--help" ]]; then
    print_help
    exit
fi

set -u
job_script=$1
############################################
CONTAINER=`cat ${job_script} | grep '#MRUNNER' | grep '\-\-CONTAINER=' | awk -F '=' '{print $2}'`
NODES=`cat ${job_script} | grep '#MRUNNER' | grep '\-\-NODES=' | awk -F '=' '{print $2}'`
RCMD="pdsh -R ssh -w ${NODES} docker exec ${CONTAINER}"
MASTER_ADDR=`${RCMD} 'echo rank%n, $(hostname -I)' | grep rank0 | awk '{print $3}'`
NUM_NODES=`${RCMD} "echo rank%n" | wc -l`
WORKDIR=`pwd`
TASK_ID="mrunner-`cat /proc/sys/kernel/random/uuid`"

ENVs=(
    NUM_NODES=${NUM_NODES}
    MASTER_ADDR=${MASTER_ADDR} 
    NODE_RANK=%n
    TASK_ID=${TASK_ID}
)

function exit_task {
    cmd="ps eww -e | grep 'TASK_ID=${TASK_ID}' | xargs | cut -d ' ' -f 1 | xargs -n 1 kill"
    ${RCMD} "bash -c \" ${cmd} \" " > /dev/null 2>&1
    sleep 1
    ${RCMD} "bash -c \" ${cmd} \" " > /dev/null 2>&1
    echo Mrunner exit!
}
trap exit_task SIGINT SIGTERM ERR EXIT

cmd="cd ${WORKDIR}; ${ENVs[@]} bash ${@:1}"
${RCMD} "bash -c \"source /etc/profile; source /root/.bashrc; ${cmd} \" " 2>&1 | tee output-${TASK_ID}.log